# Site settings
title: thswave
email: thswave@gmail.com
name : thswave
description: > # this means to ignore newlines until "baseurl:"
  Try hard, Try hard!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://thswave.github.io" # the base hostname & protocol for your site
twitter_username: thswave
github_username:  thswave
pygments: true
markdown : redcarpet

# Build settings
markdown: kramdown
